#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Load pure prompt
autoload -Uz promptinit
promptinit
prompt pure

# Add npm to PATH
export PATH=~/.npm-global/bin:$PATH

# Add git aliases
alias gst='gws'
alias ga='gia'
